Repository SombreroElGringo/hondana, pull requests merged in 2018-12, with the labels that each got.

#18 Feature/map page
  client/Gulpfile.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/Header/Header.js
  client/src/components/Map/Map.js
  client/src/components/SearchBook/SearchBook.js
  client/src/pages/App/App.js
  client/src/pages/App/App.scss
  client/src/pages/BookPage/BookPage.js
  client/src/pages/BookPage/BookPage.scss
  client/src/pages/HomePage/HomePage.js
  client/src/redux/actions/app.js
  client/src/redux/index.js
  client/src/redux/reducers/app.js
  client/src/utils/redux_helpers.js
Labels: feature

#20 Add Login and Register Form
  client/src/components/HttpError/HttpError.js
  client/src/components/HttpError/HttpError.scss
  client/src/components/Login/Login.js
  client/src/components/Register/Register.js
  client/src/pages/App/App.js
  client/src/pages/AuthPage/AuthPage.js
  client/src/pages/AuthPage/AuthPage.scss
  client/src/redux/actions/auth.js
  client/src/redux/consts/app.js
  client/src/redux/index.js
  client/src/redux/reducers/auth.js
  client/src/redux/selectors/auth/getErrors.js
  client/src/redux/selectors/auth/getToken.js
  server/src/auth/auth.controller.ts
  server/test/auth/auth.spec.ts
Labels: feature

#25 fixes:
  client/src/components/Map/Map.js
  client/src/components/SearchBook/SearchBook.js
  client/src/pages/BookPage/BookPage.js
Labels: feature

#32 React tests
  client/src/__mocks__/axios.js
  client/src/__tests__/components/Book.test.js
  client/src/__tests__/index.test.js
  client/src/__tests__/pages/App.test.js
  client/src/__tests__/pages/AuthPage.test.js
  client/src/__tests__/pages/BookPage.test.js
  client/src/__tests__/pages/Detail.test.js
  client/src/__tests__/pages/NotFoundPage.test.js
  client/src/components/Book/Book.js
  client/src/components/LibraryBook/LibraryBook.js
  client/src/components/UserProfile/UserProfile.js
  client/src/pages/Detail/Detail.js
  client/src/redux/actions/app.js
Labels: test

#34 Feature/last five books real time
  client/package.json
  client/public/index.html
  client/src/components/LastFiveBooks/LastFiveBooks.js
  client/src/components/LastFiveBooks/LastFiveBooks.scss
  client/src/pages/HomePage/HomePage.js
Labels: feature

#33 Enhancement BookcaseCompoment
  client/package-lock.json
  client/src/components/Book/Book.js
  client/src/components/Book/Book.scss
  client/src/components/Bookcase/.v2/BookcaseAuthorForm.js
  client/src/components/Bookcase/.v2/BookcaseBookForm.js
  client/src/components/Bookcase/.v2/BookcaseForms.js
  client/src/components/Bookcase/.v2/BookcaseSearchAuthor.js
  client/src/components/Bookcase/Bookcase.js
  client/src/components/Bookcase/Bookcase.scss
  client/src/components/Bookcase/BookcaseHeader.js
  client/src/components/Bookcase/BookcaseList.js
  client/src/components/Bookcase/BookcaseSearchBook.js
  client/src/components/LibraryBook/LibraryBook.js
  client/src/components/Map/Map.js
  client/src/components/Rating/Rating.js
  client/src/components/Rating/Rating.scss
  client/src/components/SearchBook/SearchBook.js
  client/src/components/UserProfile/UserProfile.js
  client/src/components/UserRating/UserRating.js
  client/src/pages/App/App.js
  client/src/pages/BookPage/BookPage.js
  client/src/pages/BookcasePage/BookcasePage.js
  client/src/pages/Detail/Detail.js
  client/src/redux/actions/app.js
  client/src/redux/actions/auth.js
  client/src/redux/actions/authors.js
  client/src/redux/actions/bookcases.js
  client/src/redux/consts/app.js
  client/src/redux/index.js
  client/src/redux/reducers/app.js
  client/src/redux/reducers/authors.js
  client/src/redux/reducers/bookcases.js
  client/src/redux/selectors/authors/getAuthors.js
  client/src/redux/selectors/bookcases/getBookIsAdded.js
  client/src/redux/selectors/bookcases/getBookIsCreated.js
  client/src/redux/selectors/bookcases/getBookIsRemoved.js
  client/src/redux/selectors/bookcases/getBookcase.js
  client/src/redux/selectors/bookcases/getError.js
  client/src/utils/api_endpoints.js
  client/src/utils/constants.js
  server/src/bookcase/bookcase.service.ts
  server/src/bookcase/models/bookcase.schema.ts
Labels: enhancement, feature

#35 feature/logout
  client/src/components/Book/Book.js
  client/src/components/Bookcase/Bookcase.js
  client/src/components/Header/Header.js
  client/src/components/LastFiveBooks/LastFiveBooks.js
  client/src/pages/App/App.js
  client/src/pages/App/App.scss
  client/src/pages/BookPage/BookPage.scss
  client/src/redux/actions/auth.js
  client/src/redux/consts/auth.js
  client/src/redux/reducers/auth.js
  client/src/utils/cookie_helpers.js
Labels: feature

#37 feature/toBookcase
  client/src/components/Header/Header.js
  server/src/auth/auth.service.ts
Labels: feature
